---
services:
  init-scheduler:
    container_name: init-scheduler
    image: debian:stable-slim
    restart: "no"
    entrypoint: ["/bin/bash", "-c"]
    command: ["ls -al /setup && ls -al /config && cp -f /setup/ofelia.ini /config/config/config.ini"]
    volumes:
      - /mnt/data/appdata/ofelia:/config:rw
      - ./config:/setup

  scheduler:
    image: mcuadros/ofelia:latest
    container_name: scheduler
    environment:
      - TZ=Europe/Amsterdam
    # user: 1000:1000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/data/appdata/ofelia/config:/etc/ofelia
      - /mnt/data/appdata/ofelia/logs:/logs:rw
    restart: unless-stopped
    networks:
      - backend
      - frontend
    depends_on:
      - init-scheduler

networks:
  backend:
    external: true
  frontend:
    external: true
